### PR TITLE
Pim 4.0 compatibility

### LINKED ISSUE #212: Compatibility with Akeneo CE 4.0
Hi group.

Is this bundle going to be compatible with Akeneo CE 4.0? And if so, could you tell us if there is any realease date?

Thanks in advance.

Best regards. 
David.

### PR DESCRIPTION
**Pull request by ghoussard**
Hello community,

I provide you this PR in order to make compatible the CustomEntityBundle with Akeneo PIM 4.0.

Changes :
- Update docker-compose stack to use akeneo/pim-php-dev:4.0 image
- Update bundle install and test documentation
- Fix some service depreciations
- Refactor integration tests to run them on Akeneo PIM 4.0 CE and EE

Unit tests are passed. Integration tests are passed on CE and EE.

Resolves #212

### CODE REVIEW

**Comment by dalarcia** [comment]
Hi @ghoussard 

Thank you very much, I will try it rigth now.

Best regards.

**Comment by jjdiaz** [comment]
Hi @ghoussard,

$ php composer.phar require "akeneo-labs/custom-entity-bundle":"4.0.*"

I got this error:

[InvalidArgumentException]
Could not find package akeneo-labs/custom-entity-bundle in a version matching 4.0.*

Regards and thnx.

**Comment by ghoussard** [comment]
Hello @jjdiaz,

While this PR is not merged, you can't install the bundle like that because 4.0 version does not exists yet.

Meanwhile, you can install it from my fork by putting that in your composer.json :

`    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/ghoussard/CustomEntityBundle"
        }
    ],
    "require": {
        "akeneo-labs/custom-entity-bundle": "4.0.x-dev"
    }
`

We say at composer to fetch the code from my fork instead of packagist. This is not a good method for production, use it **only for development or testing**.

Then, run composer install and it should works !

Regards

**Comment by jmleroux** [comment]
Hello guys,

I'm taking info to know some details about this product licence, if i can merzge it without a CLA signature signature, etc. If all is ok, i could merge this PR.
Anyway, i didn't test it because we don't use this bundle anymore and i wanted to have your confirmation it works on 4.0with this PR. A kind of code review :wink:

**Comment by aistis-** [comment]
Hi, is it good to merge? 🙂

**Comment by simoncarre** [comment]
Thank you @ghoussard!

You know who can create a new release in 4.0 for this bundle?

```
akeneo-labs/custom-entity-bundle 4.0.* -> no matching package found.
```

**Comment by simoncarre** [comment]
Hi @gplanchat,

Any news for a release creation?

**Pull request merged**
